### PR TITLE
Fix for single large tree file with gadget4_hdf5

### PR DESCRIPTION
**Pull request by MarkMos**
Added a quick if/else to avoid issues with gadget-4 hdf5 files with many trees when using only one file.

### CODE REVIEW

**Comment by manodeep** [comment]
Thanks for the proposed fix for unique galaxyid generation. What issue are you trying to solve?

Since `numfiles` is the number of files being used in a specific iteration, which the user might change between two runs. Say the first run is with `(firstfile, lastfile) = (1, 2)` and the second run is with `(firstfile, lastfile) = (3, 4)`. In both cases, `numfiles == 2` and the generated ids with your scheme will be identical, whereas the ids will be distinct with the existing scheme.

**Comment by MarkMos** [comment]
Ah, that makes sense, though I think my scheme should only affect the cases where a single file is used (as it reverts to standard behaviour for numfiles>1) - not when using two files,so (firstfile, lastfile) = (1, 1) and (firstfile, lastfile) = (2, 2) would get the same IDs, but not the scenario you suggest? (though this is of course equally bad) 

My issue is for files with many trees, `number of trees * tree multiplication factor > file multiplication factor`, so Sage exits. 

My initial "band-aid" fix was just increasing the file multiplication factor, but that is not really a scalable fix.

**Comment by manodeep** [comment]
Your case is the unlikely use case with Gadget4 hdf5 files and I would not recommend adding your fix to the main repo. 

You would be better off changing the factor within your instance of sage. One example of single-file *many* trees was the proposed Genesis-hdf5 format - see [here](https://github.com/sage-home/sage-model/blob/master/src/io/read_tree_genesis_hdf5.c#L492-L493)

**Comment by MarkMos** [comment]
Ok, in this case I recommend adding some further documentation for where to make this edit to the documentation (perhaps in the form of the error message). That would simplify the process if anyone were to have the same issue in the future.

**Comment by manodeep** [comment]
That's a good idea! Do you want to send through a PR with the new documentation?

**Pull request closed without merging**
