### PR TITLE
Update Default Plotting Flow

### PR DESCRIPTION
**Pull request by jacobseiler**
This PR greatly reworks the plotting workflow.   There a number of key features that this new workflow adds:

* Easy plotting of multiple models. By extending the variables under the `__main__` call of `analysis/allresults.py`, an arbitrary number of models can be plotted onto the same axis.  Note: Some plots used to plot extra sub-populations (e.g., the Stellar Mass Function showed red/blue galaxies).  To prevent crowding, I've added an extra flag to these plot function calls to allow plotting sub-populations when `num_models > 1`.

* Reduction of memory footprint.  Previously, all galaxies for a single model were read into RAM; that is, if `SAGE` produced 8 files of output for `z = 0`, all 8 files were read in at the beginning.  In the updated version, properties are calculated on a file-by-file basis with only binned statistics such as the stellar mass function carried over from file-to-file.  

For some plots we create scatter plots using a random subsample of galaxies (e.g., `sSFR vs Mstar`). For these, we draw a weighted sample of galaxies from the file and add the relevant properties to a list that is carried across files.

* Clean.  I have attempted to keep consistent style across throughout the workflow to allow better code comprehensibility.  To this end, I've split the workflow into 3 files, `allresults.py`, `plots.py` and `observations.py`.

`allresults.py` is intended to be the main driver module. A first time user would only need to touch this file and the variables in the `__main__` call.  This module then handles reading all the galaxy data and calculating the relevant properties.

`plots.py` as the name suggests, performs all the plotting.

`observations.py` contains observational data that is plotted on some Figures. Separated so we can easily extend it when more data becomes available.

I've copied examples of the plots to `/fred/oz004/jseiler/new_allresults_PR/` as Github won't allow me to `tar` them up and add here...

TO-DOS
=====

There are a few things that need to be done before this should be pulled into `master`

* Docstrings.  Need to do a pass and update all of these. In particular, should the `Model` class docstring list ALL the attributes here?  This would be a lot as each model contains all the Mass Functions/gas masses/velocities etc.

* Colour scheme. There needs to be a discussion regarding the default colours we provide here.

* There are a number of questions in the [Projects Board](https://github.com/sage-home/sage-model/projects/7). 

I think that's all from the top of my head right now...

### CODE REVIEW

**Comment by manodeep** [comment]
@jacobseiler Do we want to decide on the code-formatting? And do we want to setup readthedocs/gh-pages to host the docs?

Also, the review will have to wait till at least mid-week. I assume this PR is not urgent...

**Comment by jacobseiler** [comment]
@manodeep Yes the code-formatting should be decided upon.  There isn't too many in the [Consitency Project](https://github.com/sage-home/sage-model/projects/6) that applies to Python.  Perhaps we could discuss this at the group meeting tomorrow.

For RTD, I don't think it's an immediate issue/one at all.  Although I think it should be discuss a bit more.

And yes, this isn't an urgent PR.

**Comment by darrencroton** [comment]
Nice work Jacob. Is there a need to set aside 30min or similar and discuss things in person?

**Comment by jacobseiler** [comment]
Yup I think that'd be a great idea. I'm free anytime except 2-3pm Monday and 8:30-10:30am Wednesday :)

**Comment by darrencroton** [comment]
1pm Wed? Let's take the time-finding over to Slack though.

**Comment by manodeep** [comment]
One thing I had noted earlier -- the recommended approach to using `pylab` is now `import matplotlib.pyplot as plt`

**Comment by manodeep** [comment]
And we might want to use Qin's [astrodatapy package](https://github.com/qyx268/astrodatapy)

**Comment by jacobseiler** [comment]
I think we should put consideration into checking for a Latex distribution.  Trying to run the new workflow with @marcus-cehun broke because there wasn't a working TeX installed.  It's only required for making nice labels so it should still work ideally.

Not sure how to do this without a bunch of `if-else` statements...

**Comment by manodeep** [comment]
Does removing the `useTex = True` or removing the `r` in front of `r$<string>$` work?

**Comment by jacobseiler** [comment]
(Somehow completely messed up and merged HDF5 changes into here.  Reopening as new PR #9 )

**Pull request closed without merging**
